repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version (Used for linting)
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --preview ]
      - id: ruff-format
        args: [ --preview ]
